version: '3'

services:
  wizards_processor:
    container_name: python
    build: application
    command: python AppStart.py
    depends_on:
      - db
    env_file:
      - ./.env.dev
    network_mode: host
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wizards
